### ISSUE TITLE
Info about this?

### ISSUE THREAD

**Issue by FedeltaMedia** [easeq/magento2-page-cache-404#1]
Hi, is there any info available on this?
I'm having issues on Magento 2 homepage giving random 404's and I need to find out why. Could this extension help?

Please explain what it does :)

**Comment by easeq** [comment]
This fixes the issue where Magento 2 caches 404 page as the content of the URL and returns a 404 page a day or so after clearing page cache and needs clearing page cache for the actual page to show up. This extension checks for the actual page response when the cached response is 404.
